
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 31 01:03:00 IRDT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 23;
  public static final int BRACKETS = 48;
  public static final int EQUALS = 44;
  public static final int RIGHTPAREN = 37;
  public static final int MULL = 26;
  public static final int DOUBLE = 5;
  public static final int SEMI = 32;
  public static final int T_DOUBLELITERAL = 52;
  public static final int INTERFACE = 9;
  public static final int INT = 3;
  public static final int LESS = 29;
  public static final int FOR = 13;
  public static final int MINUS = 24;
  public static final int OPENAC = 40;
  public static final int LEFTPAREN = 36;
  public static final int AND = 46;
  public static final int READINTEGER = 22;
  public static final int LESSEQUAL = 43;
  public static final int OR = 47;
  public static final int BOOL = 4;
  public static final int COMMA = 33;
  public static final int CLASS = 2;
  public static final int T_INTLITERAL = 51;
  public static final int DIV = 27;
  public static final int NEWARRAY = 20;
  public static final int PLUS = 25;
  public static final int ASSIGN = 35;
  public static final int IF = 15;
  public static final int EXCLAMATION = 31;
  public static final int THIS = 11;
  public static final int DOT = 34;
  public static final int BIGEQUAL = 42;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int T_STRINGLITERAL = 50;
  public static final int CLOSEBRACKET = 39;
  public static final int PERCENT = 28;
  public static final int NULL = 10;
  public static final int BREAK = 18;
  public static final int BIGGER = 30;
  public static final int VOID = 8;
  public static final int ELSE = 16;
  public static final int OPENBRACKET = 38;
  public static final int NOTEQUALS = 45;
  public static final int WHILE = 14;
  public static final int EXTENDS = 7;
  public static final int STRING = 6;
  public static final int T_BOOLEANLITERAL = 53;
  public static final int CLOSEAC = 41;
  public static final int T_ID = 49;
  public static final int IMPLEMENTS = 12;
  public static final int PRINT = 21;
}

